project:
  type: book
  output-dir: docs

book:
  title: "MathNotes"
  author: "Jonas Benjamin Rose Aldous"
  date: last-modified
  date-format: long
  sidebar:
    title: "MathNotes"
    search: true
  
  chapters:
    - index.qmd

    - part: Chapters/Calculus/Introduction.qmd
      chapters:
        - Chapters/Calculus/Differential.qmd
        - Chapters/Calculus/Differential_Equations.qmd
        - Chapters/Calculus/Integration.qmd
        
    - part: Chapters/Linear_Algebra/Introduction.qmd
      chapters:
        - Chapters/Linear_Algebra/Matrix.qmd

    - part: Chapters/Probability/Introduction.qmd
      chapters:
        - Chapters/Probability/Stochastic_Variables.qmd

    - part: "Data Science"
      chapters:
        - Chapters/Data_Science/Statistical_Power.qmd
        - Chapters/Data_Science/Missing_Data.qmd
        - Chapters/Data_Science/Causality.qmd
        - Chapters/Data_Science/Bootstrap.qmd

    - part: Chapters/Statistical_Models/Introduction.qmd
      chapters:
        - Chapters/Statistical_Models/Covariance_Structures.qmd
        - Chapters/Statistical_Models/Logistic_Regression.qmd
        - Chapters/Statistical_Models/Linear_Regression.qmd
        - Chapters/Statistical_Models/Linear_Mixed_Model.qmd
        - Chapters/Statistical_Models/Non-linear_Mixed_Model.qmd

    - part: Chapters/Survival_Analysis/Introduction.qmd
      chapters:
        - Chapters/Survival_Analysis/Survival_Function.qmd
        - Chapters/Survival_Analysis/Hazard_Function.qmd
        - Chapters/Survival_Analysis/Censoring.qmd
        - Chapters/Survival_Analysis/Kaplan-Meier.qmd
        - Chapters/Survival_Analysis/Cox.qmd
        - Chapters/Survival_Analysis/Competing_Risk.qmd

    - part: Chapters/Time_Series/Introduction.qmd
      chapters:
        - Chapters/Time_Series/ARMA.qmd
        
    - part: Chapters/Spatial_Statistics/Introduction.qmd
      chapters:
        - Chapters/Spatial_Statistics/Summary_Statistics.qmd

  appendices: 
    - Chapters/Probability/APP-Stochastic_Variables.qmd

reference-section-title: "References"
bibliography:
  - Bibliography/articles.bib
  - Bibliography/books.bib

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css
    page-layout: full
    grid:
      body-width: 1200px

nameref:
  section-number: true