project:
  type: book
  output-dir: docs

book:
  title: "MathNotes"
  author: "Jonas Benjamin Rose Aldous"
  date: last-modified
  date-format: long
  sidebar:
    title: "MathNotes"
    search: true
  repo-url: https://github.com/loprtq/MathNotes
  
  chapters:
    - index.qmd

    - part: Chapters/Probability/Introduction.qmd
      chapters:
        - Chapters/Probability/Stochastic_Variables.qmd

    - part: Chapters/Statistical_Models/Introduction.qmd
      chapters:
        - Chapters/Statistical_Models/Logistic_Regression.qmd
        - Chapters/Statistical_Models/Linear_Regression.qmd
        - Chapters/Statistical_Models/Linear_Mixed_Model.qmd
        - Chapters/Statistical_Models/Mixed_Model_for_Repeated_Measures.qmd
        - Chapters/Statistical_Models/Non-linear_Mixed_Model.qmd
        - Chapters/Statistical_Models/Covariance_Structures.qmd

    - part: Chapters/Survival_Analysis/Introduction.qmd
      chapters:
        - Chapters/Survival_Analysis/Survival_Function.qmd
        - Chapters/Survival_Analysis/Hazard_Function.qmd
        - Chapters/Survival_Analysis/Censoring.qmd
        - Chapters/Survival_Analysis/Kaplan-Meier.qmd
        - Chapters/Survival_Analysis/Cox.qmd
        - Chapters/Survival_Analysis/Competing_Risk.qmd

    - part: Chapters/Time_Series/Introduction.qmd
      chapters:
        - Chapters/Time_Series/ARMA.qmd

  appendices: 
    - Chapters/Probability/APP-Stochastic_Variables.qmd

reference-section-title: "References"
bibliography:
  - Bibliography/articles.bib
  - Bibliography/books.bib

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css
    page-layout: full
    grid:
      body-width: 1200px

nameref:
  section-number: true